def github name, version, options = {}
  options[:repo] ||= "boxen/puppet-#{name}"
  mod name, version, :github_tarball => options[:repo]
end

github 'boxen', '0.0.26'
github 'nodejs', '1.0.0'
github 'nvm', '1.0.0'
